version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - VAULT_URL=${VAULT_URL}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - SECRET_PATH=${SECRET_PATH}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0
